### ISSUE TITLE
Adapter updateItem

### ISSUE THREAD

**Issue by SemihAkar** [kevinsawicki/wishlist#13]
There is now way to update an item after it is added to the adapter. An I cannot update items because it is private. So there should be some method like updateItem( position, item)

**Comment by barend** [comment]
I handle this by having a custom ViewGroup as the adapter item view class, and have it register an event listener on its data item (a.k.a. observer pattern). No need for extra call flows through the adapter. Just make sure the custom view unregisters itself from its previous data item when it's recycled.

Failing that, there's always `notifyDataSetChanged()`.

**Comment by SemihAkar** [comment]
nice way.
