### ISSUE TITLE
Release 0.9 doesn't include libs/android_support_v4.jar

### ISSUE THREAD

**Issue by gjtorikian** [kevinsawicki/wishlist#5]
This causes a few errors and the project won't compile.

**Comment by kevinsawicki** [comment]
The 0.9 release compiles, or else it would not have been deployable to Maven Central.

What command are you running to build?

**Comment by gjtorikian** [comment]
After fetching a project that uses wishlist, I bumped the `com.github.kevinsawicki` from 0.8 to 0.9. I ran `mvn clean install`, and opened up the project in Eclipse. There was no libs folder there, so I had to copy one in.

**Comment by kevinsawicki** [comment]
The support library is referenced as a [Maven dependency](https://github.com/kevinsawicki/wishlist/blob/master/lib/pom.xml#L60-L64), so you will need to bring all of those into your `libs` if you want to build in Eclipse.

Closing this out as the only officially supported build system is Maven for this project.
