### ISSUE TITLE
Cannot Find Appropriate Platform Level

### ISSUE THREAD

**Issue by donnfelker** [kevinsawicki/wishlist#6]
Hi Kevin, on the Android Bootstrap project, we have the following issue: https://github.com/donnfelker/android-bootstrap/issues/25

Unfortunately this seems to still be prevalent in the latest version of IntellIiJ and I'm not sure whats causing it. Do you have any idea why this library might be doing this? In All of the projects I use wishlist I have to perform the same hack that I provided in the comments today. 

Any idea? Are we using Wishlist incorrectly or including it incorrectly?

**Comment by kevinsawicki** [comment]
Hmm, I'm really not sure, I've never used IntelliJ, I would definitely accept any pull requests needed for tweaking any included metadata or what not to get things working for IntelliJ users though.

**Comment by donnfelker** [comment]
Ok, I'll look into it and see what might the issue.

Thanks,

Donn

**Comment by donnfelker** [comment]
Looks like an IntellIJ issue. Fest Android had the same issue. Fixed in 12.1.4: http://youtrack.jetbrains.com/issue/IDEA-104800 I'll close this.

**Comment by kevinsawicki** [comment]
Awesome, thanks for letting me know.
